import "./scripts/dom.js";
import "./scripts/functions.js";
import "./scripts/globals.js";
import "./scripts/generics.js";
import "./scripts/inmutability.js";
import "./scripts/exhaustive-checking.js";
import "./scripts/tupples.js";
import "./scripts/narrowing.js";
import "./scripts/branded-types.js";
